POST http://localhost:3000/api/situacoes  HTTP/1.1
content-type: application/json

{
    "nome" : "Batatinha 123"
}

###
GET http://localhost:3000/api/situacoes  HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/api/situacoes/64deaae176a5e29bd7373187  HTTP/1.1
content-type: application/json

###
PUT http://localhost:3000/api/situacoes/64deaae176a5e29bd7373187  HTTP/1.1
content-type: application/json

{
    "nome" : "Danca da maozinha"
}

###
DELETE http://localhost:3000/api/situacoes/64deaae176a5e29bd7373187  HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/api/tarefas  HTTP/1.1
content-type: application/json

{
    "assunto" : "Ligação",
    "data" : "2023-08-17",
    "descricao" :"Ligar pro Ciclano",
    "contato" :"Ciclano",
    "situacao" :  {
    "_id": "64de93a3a744360827253b55",
    "nome": "Cancelado",
    "createdAt": "2023-08-17T21:39:47.586Z",
    "updatedAt": "2023-08-17T23:54:00.134Z",
    "__v": 0
  }
}